Add update cycle documentation
countr/website pull request #182
Opened 2022-08-15 10:22 UTC by promise

2022-08-15 12:25 UTC, itzJOHv approved these changes

2022-08-15 12:40 UTC, Ta1al approved these changes

2022-08-15 12:42 UTC, Aditya20-ai requested changes
Change "We make new updates to Countr every week" to "We update Countr every week" or "We push updates to Countr every week"

2022-08-16 07:22 UTC, Aditya20-ai approved these changes

2022-08-16 07:35 UTC, itzJOHv approved these changes

2022-08-16 07:36 UTC, merged